### ISSUE TITLE
error: attribute 'overlay' missing

### ISSUE THREAD

**Issue by Mageas** [jakehamilton/neovim#2]
Hello, I am fairly new to NixOS, and I can't wrap my head around this error.
```
error: attribute 'overlay' missing

       at /nix/store/gwwr3pq93wb2m442imcpy75fkkg81lxn-source/flake.nix:73:9:

           72|       overlays = with inputs; [
           73|         neovim.overlay
             |         ^
           74|         flake.overlay
       Did you mean overlays?
(use '--show-trace' to show detailed location information)
```

I'm importing Snowfall Lib and the overlays into my NixOS config like yours. My config is heavily based on yours.
```nix
# Snowfall Lib
snowfall-lib.url = "github:snowfallorg/lib/dev";
snowfall-lib.inputs.nixpkgs.follows = "nixpkgs";
```

```nix
overlays = with inputs; [
  neovim.overlay
  flake.overlay
];
```

I have tried multiple solutions, but I still have the same error.

**Comment by jakehamilton** [comment]
Hey! Sorry about this, I recently updated this flake to use a development version of Snowfall Lib which gets rid of the old, deprecated `overlay` output. To get neovim from this flake you can use `inputs.neovim.overlays.default`.

I've gone ahead and updated the readme as well to correct this.

**Comment by jakehamilton** [comment]
For reference, here is what it looks like when I pull the overlay in:

https://github.com/jakehamilton/config/blob/ab3bdade824335d44aba53cfb2bdd4322635b390/flake.nix#L171

**Comment by Mageas** [comment]
Thank you very much, I didn't notice that you had changed neovim in flake.nix.
Keep up the good work!
